title: Bellatrix Sampe Rompon
logo: /assets/img/formal photo.png
#description: Bachelor Degree of Telecommunications Engineering with 2 years of experience in developing and implementing Robotic Process Automation (RPA). Experienced in creating RPA systems that used in banking, finance, insurance, and human resource fields. Can work together in a team, have good communication skills, and quickly learn new things.
show_downloads: false
theme: jekyll-theme-minimal
